#!/bin/bash

# File to generate a readme.html from a readme in textile format

# Assumes a command of the format (with appropriate comments removed)

# File: textile2html
# ---------------------
#!/usr/bin/env ruby

#require 'rubygems'
#gem 'RedCloth'
#require 'redcloth'
#puts RedCloth.new( ARGF.read ).to_html

# ---------------------

read -d '' HTML_HEADER << 'HTML_HEADER'
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>xen_create_appliance - README</title>  
  </head>
  
  <body>
HTML_HEADER
read -d '' HTML_FOOTER << 'HTML_FOOTER'
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
  </body>
</html>
HTML_FOOTER

readmeFileName='readme.html'
echo $HTML_HEADER >${readmeFileName}
textile2html readme.textile >>${readmeFileName}
echo $HTML_FOOTER >>${readmeFileName}

read -d '' HTML_HEADER_1 << 'HTML_HEADER_1'
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>xen_create_appliance - README LVM</title>  
  </head>
  
  <body>
HTML_HEADER_1

read -d '' HTML_FOOTER_1 << 'HTML_FOOTER_1'
  </body>
</html>
HTML_FOOTER_1

readmeFileName='readme_lvm.html'
echo $HTML_HEADER_1 >${readmeFileName}
textile2html readme_lvm.textile >>${readmeFileName}
echo $HTML_FOOTER_1 >>${readmeFileName}


read -d '' HTML_HEADER_2 << 'HTML_HEADER_2'
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <title>xen_create_appliance - README CENTOS LOCAL MIRROR</title>  
  </head>
  
  <body>
HTML_HEADER_2

read -d '' HTML_FOOTER_2 << 'HTML_FOOTER_2'
  </body>
</html>
HTML_FOOTER_2

readmeFileName='readme_local_centos_mirror.html'
echo $HTML_HEADER_2 >${readmeFileName}
textile2html readme_local_centos_mirror.textile >>${readmeFileName}
echo $HTML_FOOTER_2 >>${readmeFileName}
