#!/bin/bash

#
# Script to create Xen-based VMs from scratch on CentOS 5
#
# See README for pre-requisites etc.
# 
# tflynn projects@olioinfo.net
#
# May be freely redistributed
#

DEBUG=true

if [[ ${DEBUG} != true ]] ; then
  if [[ `whoami` != 'root' ]] ; then
    echo "Please run this script as root"
    exit 1
  fi
fi


if [[ $# != 5 ]] ; then
  echo "Usage: xen_make_appliance [binaries directory] [configuration directory] [appliance name] [memory size in MB] [disk_size in GB]"
  exit 1
fi

###############
# Set up a whole bunch of variables
###############

binDir=$1
configurationDir=$2
applianceName=$3
applianceNameLowerCase=`echo ${applianceName} | tr '[:upper:]' '[:lower:]'`
memorySizeMB=$4
diskSizeGB=$5
diskSizeMB=$(((diskSizeGB * 1000) - 100))

vmMacAddresses="${configurationDir}/vm_mac_addresses"
dropboxBaseUrlFile="${configurationDir}/dropbox_base_url"
vmMountCmds=${configurationDir}/mount_all_vms
vmStartCmds=${configurationDir}/start_all_vms

# Load configuration files

if [[ ! -e $dropboxBaseUrlFile ]] ; then
  echo "Please create the file ${dropboxBaseUrlFile} with the URL for the base of the Xen configuration file tree."
  exit 1
fi

source $dropboxBaseUrlFile

configFile="${configurationDir}/xen_make_appliance.config"

if [[ -e ${configFile} ]] ; then
  source ${configFile}
else
  echo "No configuration file found. Using defaults."
fi

# Set variables based on configuration file settings or defaults
  
logicalVolumeGroupName=${LOGICAL_VOLUME_GROUP_NAME:-vm_lvs}
logicalVolumePrefix=${LOGICAL_VOLUME_PREFIX:-lvol_}  
logcialVolumeStripes=${LOGICAL_VOLUME_TOTAL_STRIPES:-5}
baseVMMountPoint=${BASE_VM_MOUNT_POINT:-xenvms}
backupFileExtension=${BACKUP_FILE_EXTENSION:-bak}


########
# VM Setup starts
########
  
# Create the logical volume to hold the VM

#sudo lvcreate -i${logcialVolumeStripes} -L${diskSizeGB}G -n${logicalVolumePrefix}${applianceNameLowerCase} ${logicalVolumeGroupName}
#sudo mkfs -t ext3 /dev/${logicalVolumeGroupName}/${logicalVolumePrefix}${applianceNameLowerCase}
#sudo mkdir -p ${baseVMMountPoint}/${applianceName}
#sudo mount /dev/${logicalVolumeGroupName}/${logicalVolumePrefix}${applianceNameLowerCase}  ${baseVMMountPoint}/${applianceName}

echo "sudo lvcreate -i${logcialVolumeStripes} -L${diskSizeGB}G -n${logicalVolumePrefix}${applianceNameLowerCase} ${logicalVolumeGroupName}"
echo "sudo mkfs -t ext3 /dev/${logicalVolumeGroupName}/${logicalVolumePrefix}${applianceNameLowerCase}"
echo "sudo mkdir -p ${baseVMMountPoint}/${applianceName}"
echo "sudo mount /dev/${logicalVolumeGroupName}/${logicalVolumePrefix}${applianceNameLowerCase}  ${baseVMMountPoint}/${applianceName}"

# Save off VM mount cmd
touch ${vmMountCmds}
cp ${vmMountCmds} ${vmMountCmds}.${backupFileExtension}
echo "sudo mount /dev/${logicalVolumeGroupName}/${logicalVolumePrefix}${applianceNameLowerCase}  ${baseVMMountPoint}/${applianceName}" >> ${vmMountCmds}.${backupFileExtension}
uniq < ${vmMountCmds}.${backupFileExtension} >${vmMountCmds}
chmod a+x ${vmMountCmds}

# Create the VM itself
#cd ${baseVMMountPoint}/${applianceName}
#dd if=/dev/zero of=appliance-base.img oflag=direct bs=1M seek=${diskSizeMB} count=1
#wget http://dl.dropbox.com/u/12189743/xen/${applianceName}/appliance-base.install.cfg
#wget http://dl.dropbox.com/u/12189743/xen/${applianceName}/appliance-base.cfg


# Edit the config files

# Get the next MAC address
nextMacAddress=0
if [[ -e ${vmMacAddresses} ]] ; then
  while read inputLine
  do
    nextMacAddress=inputLine
    break
  done < ${vmMacAddresses}
fi
nextMacAddress=$((nextMacAddress + 1))
echo "nextMacAddress ${nextMacAddress}"
echo "${nextMacAddress}" > ${vmMacAddresses}
nextMacAddressHex=`printf "%02X" ${nextMacAddress}`

read -d '' APPLIANCE_BASE_CONFIGURATION << APPLIANCE_BASE_CONFIGURATION_DOC
# Xen Configuration for appliance-base
name   = "appliance-base"
memory = "${memorySizeMB}"
disk   = ['tap:aio:/xen/appliance-base/appliance-base.img,xvda,w',]
vif    = ['bridge=xenbr0,mac=00:16:3e:00:00:${nextMacAddressHex}',]
vcpus  = 1

bootloader ="/usr/bin/pygrub"
on_reboot  = 'restart'
on_crash   = 'restart'
APPLIANCE_BASE_CONFIGURATION_DOC

echo "${APPLIANCE_BASE_CONFIGURATION}"


echo "cd /xenvms/${applianceName}"
echo "dd if=/dev/zero of=appliance-base.img oflag=direct bs=1M seek=${diskSizeMB} count=1"
echo "wget http://dl.dropbox.com/u/12189743/xen/${applianceName}/appliance-base.install.cfg"
echo "wget http://dl.dropbox.com/u/12189743/xen/${applianceName}/appliance-base.cfg"


# Initialize the VM the first time
#xm create -c appliance-base.install.cfg
echo "xm create -c appliance-base.install.cfg"
# Start it up the second time with standard options
#xm create -c appliance-base.cfg
echo "xm create -c appliance-base.cfg"

# Add to VM start command
touch ${vmStartCmds}
cp ${vmStartCmds} ${vmStartCmds}.${backupFileExtension}
echo "pushd /xenvms/${applianceName} 2>%1 >/dev/null ; xm create -c appliance-base.cfg ; popd 2>%1 >/dev/null" >> ${vmStartCmds}.${backupFileExtension}
uniq < ${vmStartCmds}.${backupFileExtension} >${vmStartCmds} 
chmod a+x ${vmStartCmds}




